name: codspeed-benchmarks-test

on:
    push:
        branches:
            - 'main'
    pull_request:
    workflow_dispatch:

jobs:
    benchmarks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11.1
                  # More info: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
                  registry-url: 'https://registry.npmjs.org'
            - name: Use node_modules cache
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: yarn-node-20-lock-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      yarn-node-20-lock-
            - run: yarn install --frozen-lockfile
            - name: Run benchmarks
              uses: CodSpeedHQ/action@v3
              with:
                run: 'yarn bench'
              env:
                CODSPEED_DEBUG: true
